# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/suvarna/Documents/Personal_Project/local-version-control.git/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/suvarna/Documents/Personal_Project/local-version-control.git/trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/suvarna/Documents/Personal_Project/local-version-control.git/trunk/CMakeFiles /home/suvarna/Documents/Personal_Project/local-version-control.git/trunk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/suvarna/Documents/Personal_Project/local-version-control.git/trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lovec

# Build rule for target.
lovec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lovec
.PHONY : lovec

# fast build rule for target.
lovec/fast:
	$(MAKE) -f CMakeFiles/lovec.dir/build.make CMakeFiles/lovec.dir/build
.PHONY : lovec/fast

create-repo.o: create-repo.cpp.o
.PHONY : create-repo.o

# target to build an object file
create-repo.cpp.o:
	$(MAKE) -f CMakeFiles/lovec.dir/build.make CMakeFiles/lovec.dir/create-repo.cpp.o
.PHONY : create-repo.cpp.o

create-repo.i: create-repo.cpp.i
.PHONY : create-repo.i

# target to preprocess a source file
create-repo.cpp.i:
	$(MAKE) -f CMakeFiles/lovec.dir/build.make CMakeFiles/lovec.dir/create-repo.cpp.i
.PHONY : create-repo.cpp.i

create-repo.s: create-repo.cpp.s
.PHONY : create-repo.s

# target to generate assembly for a file
create-repo.cpp.s:
	$(MAKE) -f CMakeFiles/lovec.dir/build.make CMakeFiles/lovec.dir/create-repo.cpp.s
.PHONY : create-repo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... lovec"
	@echo "... rebuild_cache"
	@echo "... create-repo.o"
	@echo "... create-repo.i"
	@echo "... create-repo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

